project_id = "vrawwiqeutbqqdzkhrax"

[functions.get-available-slots]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.get-services]
verify_jwt = false

[functions.get-barbers]
verify_jwt = false

[functions.create-employee]
verify_jwt = true

[functions.send-report-email]
verify_jwt = true

[functions.send-automated-report]
verify_jwt = false

[functions.process-scheduled-reports]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true